PKG_NAME = autossh
PKG_VERS = 1.4e
PKG_EXT = tgz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://www.harding.motd.ca/autossh/
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS =

HOMEPAGE = http://www.harding.motd.ca/autossh/
COMMENT  = Automatically restart SSH sessions and tunnels
LICENSE  = BSD

PATCHES_LEVEL = 1
GNU_CONFIGURE = 1
CONFIGURE_ARGS =

include ../../mk/spksrc.cross-cc.mk
